package br.maua.cic303;

import java_cup.runtime.Symbol;

parser code {:
    public void syntax_error(Symbol current) {
        throw new CompilerException("Erro sintático");
    }
:};

terminal IF, THEN, ELSE, WHILE;
terminal ID, NUMBER;
terminal ASSIGN, ADD_OP, MUL_OP, REL_OP;
terminal LPAREN, RPAREN, LBRACE, RBRACE, SEMI;
terminal ERROR;
terminal LOWER_THAN_ELSE;

non terminal program;
non terminal stmt_list;
non terminal stmt;
non terminal assign_stmt;
non terminal if_stmt;
non terminal while_stmt;
non terminal block_stmt;
non terminal expr;

precedence nonassoc LOWER_THAN_ELSE;
precedence nonassoc ELSE;

precedence left REL_OP;
precedence left ADD_OP;
precedence left MUL_OP;

start with program;

program ::= stmt_list
;

stmt_list ::=
      stmt_list stmt
    |
;

stmt ::=
      assign_stmt
    | if_stmt
    | while_stmt
    | block_stmt
    | SEMI
;

assign_stmt ::=
    ID ASSIGN expr SEMI
;

if_stmt ::=
      IF LPAREN expr RPAREN THEN stmt %prec LOWER_THAN_ELSE
    | IF LPAREN expr RPAREN THEN stmt ELSE stmt
;

while_stmt ::=
    WHILE LPAREN expr RPAREN stmt
;

block_stmt ::=
    LBRACE stmt_list RBRACE
;

expr ::=
      expr ADD_OP expr
    | expr MUL_OP expr
    | expr REL_OP expr
    | LPAREN expr RPAREN
    | ID
    | NUMBER
;